### ISSUE TITLE
Non-asciidoc imports affected?

### ISSUE THREAD

**Issue by nomeata** [johannesjh/asciidoctor-indir_ext#1]
https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/include-directive.adoc describes how to include code in your files, e.g. using
```
[source,java]
----
include::{sourcedir}/org/asciidoctor/Asciidoctor.java[]
----
```

But if I do that in a project that uses `indir_ext`, I get
```
:indir: /some/path/to/the/code
```
in the listing. That’s of course horrible!

According to https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/include-directive.adoc#asciidoc-vs-non-asciidoc-files asciidoc only treats files ending in .asciidoc, .adoc, .ad, .asc, or .txt as Asciidoc; presumably this extension should do the same.

**Comment by johannesjh** [comment]
Thank you for pointing this out, I think you are right. To fix the issue, we could add a return statement after `extension.rb # line 22` and return unmodified content if the included filename does not end with `.asciidoc`, `.adoc`, `.ad`, `.asc`, or `.txt`. 

https://github.com/johannesjh/asciidoctor-indir_ext/blob/897f1bf3d02314006cea8967958a5b8f82b9aa14/lib/asciidoctor/indir_ext/extension.rb#L20-L22
