### ISSUE TITLE
Failed to load AsciiDoc document - wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by CMon** [johannesjh/asciidoctor-indir_ext#3]
I get an error in the initiliaze call of the extension above line:
```
${HOME}/.gem/ruby/3.0.0/gems/asciidoctor-include-ext-0.3.1/lib/asciidoctor/include_ext/include_processor.rb:25:in `initialize': asciidoctor: FAILED: ${HOME}/tmp/test-repo/asciidoc-test2/main.adoc: Failed to load AsciiDoc document - wrong number of arguments (given 1, expected 0) (ArgumentError)
        from ${HOME}/.gem/ruby/3.0.0/gems/asciidoctor-indir_ext-0.1.3/lib/asciidoctor/indir_ext/extension.rb:11:in `initialize'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/extensions.rb:1359:in `new'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/extensions.rb:1359:in `add_document_processor'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.17/lib/asciidoctor/extensions.rb:946:in `include_processor'
...
```
This seems to be similar to the issue from https://github.com/asciidoctor/asciidoctorj/issues/451#issuecomment-210917168 and if I apply the solution from there it works. so the simple fix would be to change `super` to `super()` here: https://github.com/johannesjh/asciidoctor-indir_ext/blob/a800e77f2dcad51c50283fd31e7a4a6504c3284e/lib/asciidoctor/indir_ext/extension.rb#L11

**Comment by johannesjh** [comment]
thank you, I followed your suggestion and released it as [v0.1.4](https://github.com/johannesjh/asciidoctor-indir_ext/releases/tag/v0.1.4)
